// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kstn/game/logic/playing_event/cell/cell_message.proto

package kstn.game.logic.playing_event.cell;

public final class CellMessage {
  private CellMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OpenCellOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OpenCell)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 index = 1;</code>
     */
    int getIndex();
  }
  /**
   * Protobuf type {@code OpenCell}
   */
  public  static final class OpenCell extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OpenCell)
      OpenCellOrBuilder {
    // Use OpenCell.newBuilder() to construct.
    private OpenCell(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OpenCell() {
      index_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private OpenCell(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              index_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kstn.game.logic.playing_event.cell.CellMessage.internal_static_OpenCell_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kstn.game.logic.playing_event.cell.CellMessage.internal_static_OpenCell_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kstn.game.logic.playing_event.cell.CellMessage.OpenCell.class, kstn.game.logic.playing_event.cell.CellMessage.OpenCell.Builder.class);
    }

    public static final int INDEX_FIELD_NUMBER = 1;
    private int index_;
    /**
     * <code>int32 index = 1;</code>
     */
    public int getIndex() {
      return index_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (index_ != 0) {
        output.writeInt32(1, index_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (index_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, index_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof kstn.game.logic.playing_event.cell.CellMessage.OpenCell)) {
        return super.equals(obj);
      }
      kstn.game.logic.playing_event.cell.CellMessage.OpenCell other = (kstn.game.logic.playing_event.cell.CellMessage.OpenCell) obj;

      boolean result = true;
      result = result && (getIndex()
          == other.getIndex());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getIndex();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static kstn.game.logic.playing_event.cell.CellMessage.OpenCell parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.playing_event.cell.CellMessage.OpenCell parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.cell.CellMessage.OpenCell parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.playing_event.cell.CellMessage.OpenCell parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.cell.CellMessage.OpenCell parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.playing_event.cell.CellMessage.OpenCell parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.cell.CellMessage.OpenCell parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kstn.game.logic.playing_event.cell.CellMessage.OpenCell parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.cell.CellMessage.OpenCell parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static kstn.game.logic.playing_event.cell.CellMessage.OpenCell parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.cell.CellMessage.OpenCell parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kstn.game.logic.playing_event.cell.CellMessage.OpenCell parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(kstn.game.logic.playing_event.cell.CellMessage.OpenCell prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OpenCell}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OpenCell)
        kstn.game.logic.playing_event.cell.CellMessage.OpenCellOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kstn.game.logic.playing_event.cell.CellMessage.internal_static_OpenCell_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kstn.game.logic.playing_event.cell.CellMessage.internal_static_OpenCell_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kstn.game.logic.playing_event.cell.CellMessage.OpenCell.class, kstn.game.logic.playing_event.cell.CellMessage.OpenCell.Builder.class);
      }

      // Construct using kstn.game.logic.playing_event.cell.CellMessage.OpenCell.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        index_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kstn.game.logic.playing_event.cell.CellMessage.internal_static_OpenCell_descriptor;
      }

      public kstn.game.logic.playing_event.cell.CellMessage.OpenCell getDefaultInstanceForType() {
        return kstn.game.logic.playing_event.cell.CellMessage.OpenCell.getDefaultInstance();
      }

      public kstn.game.logic.playing_event.cell.CellMessage.OpenCell build() {
        kstn.game.logic.playing_event.cell.CellMessage.OpenCell result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public kstn.game.logic.playing_event.cell.CellMessage.OpenCell buildPartial() {
        kstn.game.logic.playing_event.cell.CellMessage.OpenCell result = new kstn.game.logic.playing_event.cell.CellMessage.OpenCell(this);
        result.index_ = index_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kstn.game.logic.playing_event.cell.CellMessage.OpenCell) {
          return mergeFrom((kstn.game.logic.playing_event.cell.CellMessage.OpenCell)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kstn.game.logic.playing_event.cell.CellMessage.OpenCell other) {
        if (other == kstn.game.logic.playing_event.cell.CellMessage.OpenCell.getDefaultInstance()) return this;
        if (other.getIndex() != 0) {
          setIndex(other.getIndex());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        kstn.game.logic.playing_event.cell.CellMessage.OpenCell parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (kstn.game.logic.playing_event.cell.CellMessage.OpenCell) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int index_ ;
      /**
       * <code>int32 index = 1;</code>
       */
      public int getIndex() {
        return index_;
      }
      /**
       * <code>int32 index = 1;</code>
       */
      public Builder setIndex(int value) {
        
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 index = 1;</code>
       */
      public Builder clearIndex() {
        
        index_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:OpenCell)
    }

    // @@protoc_insertion_point(class_scope:OpenCell)
    private static final kstn.game.logic.playing_event.cell.CellMessage.OpenCell DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new kstn.game.logic.playing_event.cell.CellMessage.OpenCell();
    }

    public static kstn.game.logic.playing_event.cell.CellMessage.OpenCell getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OpenCell>
        PARSER = new com.google.protobuf.AbstractParser<OpenCell>() {
      public OpenCell parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new OpenCell(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OpenCell> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OpenCell> getParserForType() {
      return PARSER;
    }

    public kstn.game.logic.playing_event.cell.CellMessage.OpenCell getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OpenMultipleCellOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OpenMultipleCell)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 character = 1;</code>
     */
    int getCharacter();
  }
  /**
   * Protobuf type {@code OpenMultipleCell}
   */
  public  static final class OpenMultipleCell extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OpenMultipleCell)
      OpenMultipleCellOrBuilder {
    // Use OpenMultipleCell.newBuilder() to construct.
    private OpenMultipleCell(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OpenMultipleCell() {
      character_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private OpenMultipleCell(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              character_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kstn.game.logic.playing_event.cell.CellMessage.internal_static_OpenMultipleCell_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kstn.game.logic.playing_event.cell.CellMessage.internal_static_OpenMultipleCell_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell.class, kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell.Builder.class);
    }

    public static final int CHARACTER_FIELD_NUMBER = 1;
    private int character_;
    /**
     * <code>int32 character = 1;</code>
     */
    public int getCharacter() {
      return character_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (character_ != 0) {
        output.writeInt32(1, character_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (character_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, character_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell)) {
        return super.equals(obj);
      }
      kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell other = (kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell) obj;

      boolean result = true;
      result = result && (getCharacter()
          == other.getCharacter());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHARACTER_FIELD_NUMBER;
      hash = (53 * hash) + getCharacter();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OpenMultipleCell}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OpenMultipleCell)
        kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCellOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kstn.game.logic.playing_event.cell.CellMessage.internal_static_OpenMultipleCell_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kstn.game.logic.playing_event.cell.CellMessage.internal_static_OpenMultipleCell_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell.class, kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell.Builder.class);
      }

      // Construct using kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        character_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kstn.game.logic.playing_event.cell.CellMessage.internal_static_OpenMultipleCell_descriptor;
      }

      public kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell getDefaultInstanceForType() {
        return kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell.getDefaultInstance();
      }

      public kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell build() {
        kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell buildPartial() {
        kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell result = new kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell(this);
        result.character_ = character_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell) {
          return mergeFrom((kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell other) {
        if (other == kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell.getDefaultInstance()) return this;
        if (other.getCharacter() != 0) {
          setCharacter(other.getCharacter());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int character_ ;
      /**
       * <code>int32 character = 1;</code>
       */
      public int getCharacter() {
        return character_;
      }
      /**
       * <code>int32 character = 1;</code>
       */
      public Builder setCharacter(int value) {
        
        character_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 character = 1;</code>
       */
      public Builder clearCharacter() {
        
        character_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:OpenMultipleCell)
    }

    // @@protoc_insertion_point(class_scope:OpenMultipleCell)
    private static final kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell();
    }

    public static kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OpenMultipleCell>
        PARSER = new com.google.protobuf.AbstractParser<OpenMultipleCell>() {
      public OpenMultipleCell parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new OpenMultipleCell(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OpenMultipleCell> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OpenMultipleCell> getParserForType() {
      return PARSER;
    }

    public kstn.game.logic.playing_event.cell.CellMessage.OpenMultipleCell getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenCell_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenCell_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenMultipleCell_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenMultipleCell_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5kstn/game/logic/playing_event/cell/cel" +
      "l_message.proto\"\031\n\010OpenCell\022\r\n\005index\030\001 \001" +
      "(\005\"%\n\020OpenMultipleCell\022\021\n\tcharacter\030\001 \001(" +
      "\005B$\n\"kstn.game.logic.playing_event.cellb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_OpenCell_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OpenCell_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenCell_descriptor,
        new java.lang.String[] { "Index", });
    internal_static_OpenMultipleCell_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OpenMultipleCell_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenMultipleCell_descriptor,
        new java.lang.String[] { "Character", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
