// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kstn/game/logic/cone/cone_message.proto

package kstn.game.logic.cone;

public final class ConeMessage {
  private ConeMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConeMoveOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConeMove)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float angle = 1;</code>
     */
    float getAngle();
  }
  /**
   * Protobuf type {@code ConeMove}
   */
  public  static final class ConeMove extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConeMove)
      ConeMoveOrBuilder {
    // Use ConeMove.newBuilder() to construct.
    private ConeMove(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConeMove() {
      angle_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ConeMove(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 13: {

              angle_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kstn.game.logic.cone.ConeMessage.internal_static_ConeMove_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kstn.game.logic.cone.ConeMessage.internal_static_ConeMove_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kstn.game.logic.cone.ConeMessage.ConeMove.class, kstn.game.logic.cone.ConeMessage.ConeMove.Builder.class);
    }

    public static final int ANGLE_FIELD_NUMBER = 1;
    private float angle_;
    /**
     * <code>float angle = 1;</code>
     */
    public float getAngle() {
      return angle_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (angle_ != 0F) {
        output.writeFloat(1, angle_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (angle_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, angle_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof kstn.game.logic.cone.ConeMessage.ConeMove)) {
        return super.equals(obj);
      }
      kstn.game.logic.cone.ConeMessage.ConeMove other = (kstn.game.logic.cone.ConeMessage.ConeMove) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getAngle())
          == java.lang.Float.floatToIntBits(
              other.getAngle()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ANGLE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAngle());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static kstn.game.logic.cone.ConeMessage.ConeMove parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.cone.ConeMessage.ConeMove parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.cone.ConeMessage.ConeMove parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.cone.ConeMessage.ConeMove parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.cone.ConeMessage.ConeMove parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.cone.ConeMessage.ConeMove parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.cone.ConeMessage.ConeMove parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kstn.game.logic.cone.ConeMessage.ConeMove parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static kstn.game.logic.cone.ConeMessage.ConeMove parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static kstn.game.logic.cone.ConeMessage.ConeMove parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static kstn.game.logic.cone.ConeMessage.ConeMove parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kstn.game.logic.cone.ConeMessage.ConeMove parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(kstn.game.logic.cone.ConeMessage.ConeMove prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConeMove}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConeMove)
        kstn.game.logic.cone.ConeMessage.ConeMoveOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kstn.game.logic.cone.ConeMessage.internal_static_ConeMove_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kstn.game.logic.cone.ConeMessage.internal_static_ConeMove_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kstn.game.logic.cone.ConeMessage.ConeMove.class, kstn.game.logic.cone.ConeMessage.ConeMove.Builder.class);
      }

      // Construct using kstn.game.logic.cone.ConeMessage.ConeMove.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        angle_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kstn.game.logic.cone.ConeMessage.internal_static_ConeMove_descriptor;
      }

      public kstn.game.logic.cone.ConeMessage.ConeMove getDefaultInstanceForType() {
        return kstn.game.logic.cone.ConeMessage.ConeMove.getDefaultInstance();
      }

      public kstn.game.logic.cone.ConeMessage.ConeMove build() {
        kstn.game.logic.cone.ConeMessage.ConeMove result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public kstn.game.logic.cone.ConeMessage.ConeMove buildPartial() {
        kstn.game.logic.cone.ConeMessage.ConeMove result = new kstn.game.logic.cone.ConeMessage.ConeMove(this);
        result.angle_ = angle_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kstn.game.logic.cone.ConeMessage.ConeMove) {
          return mergeFrom((kstn.game.logic.cone.ConeMessage.ConeMove)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kstn.game.logic.cone.ConeMessage.ConeMove other) {
        if (other == kstn.game.logic.cone.ConeMessage.ConeMove.getDefaultInstance()) return this;
        if (other.getAngle() != 0F) {
          setAngle(other.getAngle());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        kstn.game.logic.cone.ConeMessage.ConeMove parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (kstn.game.logic.cone.ConeMessage.ConeMove) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float angle_ ;
      /**
       * <code>float angle = 1;</code>
       */
      public float getAngle() {
        return angle_;
      }
      /**
       * <code>float angle = 1;</code>
       */
      public Builder setAngle(float value) {
        
        angle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float angle = 1;</code>
       */
      public Builder clearAngle() {
        
        angle_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ConeMove)
    }

    // @@protoc_insertion_point(class_scope:ConeMove)
    private static final kstn.game.logic.cone.ConeMessage.ConeMove DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new kstn.game.logic.cone.ConeMessage.ConeMove();
    }

    public static kstn.game.logic.cone.ConeMessage.ConeMove getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConeMove>
        PARSER = new com.google.protobuf.AbstractParser<ConeMove>() {
      public ConeMove parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ConeMove(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConeMove> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConeMove> getParserForType() {
      return PARSER;
    }

    public kstn.game.logic.cone.ConeMessage.ConeMove getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConeAccelerateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConeAccelerate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float angle = 1;</code>
     */
    float getAngle();

    /**
     * <code>float speedStart = 2;</code>
     */
    float getSpeedStart();
  }
  /**
   * Protobuf type {@code ConeAccelerate}
   */
  public  static final class ConeAccelerate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConeAccelerate)
      ConeAccelerateOrBuilder {
    // Use ConeAccelerate.newBuilder() to construct.
    private ConeAccelerate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConeAccelerate() {
      angle_ = 0F;
      speedStart_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ConeAccelerate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 13: {

              angle_ = input.readFloat();
              break;
            }
            case 21: {

              speedStart_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kstn.game.logic.cone.ConeMessage.internal_static_ConeAccelerate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kstn.game.logic.cone.ConeMessage.internal_static_ConeAccelerate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kstn.game.logic.cone.ConeMessage.ConeAccelerate.class, kstn.game.logic.cone.ConeMessage.ConeAccelerate.Builder.class);
    }

    public static final int ANGLE_FIELD_NUMBER = 1;
    private float angle_;
    /**
     * <code>float angle = 1;</code>
     */
    public float getAngle() {
      return angle_;
    }

    public static final int SPEEDSTART_FIELD_NUMBER = 2;
    private float speedStart_;
    /**
     * <code>float speedStart = 2;</code>
     */
    public float getSpeedStart() {
      return speedStart_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (angle_ != 0F) {
        output.writeFloat(1, angle_);
      }
      if (speedStart_ != 0F) {
        output.writeFloat(2, speedStart_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (angle_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, angle_);
      }
      if (speedStart_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, speedStart_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof kstn.game.logic.cone.ConeMessage.ConeAccelerate)) {
        return super.equals(obj);
      }
      kstn.game.logic.cone.ConeMessage.ConeAccelerate other = (kstn.game.logic.cone.ConeMessage.ConeAccelerate) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getAngle())
          == java.lang.Float.floatToIntBits(
              other.getAngle()));
      result = result && (
          java.lang.Float.floatToIntBits(getSpeedStart())
          == java.lang.Float.floatToIntBits(
              other.getSpeedStart()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ANGLE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAngle());
      hash = (37 * hash) + SPEEDSTART_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getSpeedStart());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static kstn.game.logic.cone.ConeMessage.ConeAccelerate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.cone.ConeMessage.ConeAccelerate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.cone.ConeMessage.ConeAccelerate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.cone.ConeMessage.ConeAccelerate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.cone.ConeMessage.ConeAccelerate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.cone.ConeMessage.ConeAccelerate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.cone.ConeMessage.ConeAccelerate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kstn.game.logic.cone.ConeMessage.ConeAccelerate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static kstn.game.logic.cone.ConeMessage.ConeAccelerate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static kstn.game.logic.cone.ConeMessage.ConeAccelerate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static kstn.game.logic.cone.ConeMessage.ConeAccelerate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kstn.game.logic.cone.ConeMessage.ConeAccelerate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(kstn.game.logic.cone.ConeMessage.ConeAccelerate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConeAccelerate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConeAccelerate)
        kstn.game.logic.cone.ConeMessage.ConeAccelerateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kstn.game.logic.cone.ConeMessage.internal_static_ConeAccelerate_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kstn.game.logic.cone.ConeMessage.internal_static_ConeAccelerate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kstn.game.logic.cone.ConeMessage.ConeAccelerate.class, kstn.game.logic.cone.ConeMessage.ConeAccelerate.Builder.class);
      }

      // Construct using kstn.game.logic.cone.ConeMessage.ConeAccelerate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        angle_ = 0F;

        speedStart_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kstn.game.logic.cone.ConeMessage.internal_static_ConeAccelerate_descriptor;
      }

      public kstn.game.logic.cone.ConeMessage.ConeAccelerate getDefaultInstanceForType() {
        return kstn.game.logic.cone.ConeMessage.ConeAccelerate.getDefaultInstance();
      }

      public kstn.game.logic.cone.ConeMessage.ConeAccelerate build() {
        kstn.game.logic.cone.ConeMessage.ConeAccelerate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public kstn.game.logic.cone.ConeMessage.ConeAccelerate buildPartial() {
        kstn.game.logic.cone.ConeMessage.ConeAccelerate result = new kstn.game.logic.cone.ConeMessage.ConeAccelerate(this);
        result.angle_ = angle_;
        result.speedStart_ = speedStart_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kstn.game.logic.cone.ConeMessage.ConeAccelerate) {
          return mergeFrom((kstn.game.logic.cone.ConeMessage.ConeAccelerate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kstn.game.logic.cone.ConeMessage.ConeAccelerate other) {
        if (other == kstn.game.logic.cone.ConeMessage.ConeAccelerate.getDefaultInstance()) return this;
        if (other.getAngle() != 0F) {
          setAngle(other.getAngle());
        }
        if (other.getSpeedStart() != 0F) {
          setSpeedStart(other.getSpeedStart());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        kstn.game.logic.cone.ConeMessage.ConeAccelerate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (kstn.game.logic.cone.ConeMessage.ConeAccelerate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float angle_ ;
      /**
       * <code>float angle = 1;</code>
       */
      public float getAngle() {
        return angle_;
      }
      /**
       * <code>float angle = 1;</code>
       */
      public Builder setAngle(float value) {
        
        angle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float angle = 1;</code>
       */
      public Builder clearAngle() {
        
        angle_ = 0F;
        onChanged();
        return this;
      }

      private float speedStart_ ;
      /**
       * <code>float speedStart = 2;</code>
       */
      public float getSpeedStart() {
        return speedStart_;
      }
      /**
       * <code>float speedStart = 2;</code>
       */
      public Builder setSpeedStart(float value) {
        
        speedStart_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float speedStart = 2;</code>
       */
      public Builder clearSpeedStart() {
        
        speedStart_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ConeAccelerate)
    }

    // @@protoc_insertion_point(class_scope:ConeAccelerate)
    private static final kstn.game.logic.cone.ConeMessage.ConeAccelerate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new kstn.game.logic.cone.ConeMessage.ConeAccelerate();
    }

    public static kstn.game.logic.cone.ConeMessage.ConeAccelerate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConeAccelerate>
        PARSER = new com.google.protobuf.AbstractParser<ConeAccelerate>() {
      public ConeAccelerate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ConeAccelerate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConeAccelerate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConeAccelerate> getParserForType() {
      return PARSER;
    }

    public kstn.game.logic.cone.ConeMessage.ConeAccelerate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConeMove_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConeMove_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConeAccelerate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConeAccelerate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'kstn/game/logic/cone/cone_message.prot" +
      "o\"\031\n\010ConeMove\022\r\n\005angle\030\001 \001(\002\"3\n\016ConeAcce" +
      "lerate\022\r\n\005angle\030\001 \001(\002\022\022\n\nspeedStart\030\002 \001(" +
      "\002B\026\n\024kstn.game.logic.coneb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ConeMove_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ConeMove_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConeMove_descriptor,
        new java.lang.String[] { "Angle", });
    internal_static_ConeAccelerate_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ConeAccelerate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConeAccelerate_descriptor,
        new java.lang.String[] { "Angle", "SpeedStart", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
