// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kstn/game/logic/playing_event/player/player_message.proto

package kstn.game.logic.playing_event.player;

public final class PlayerMessage {
  private PlayerMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NextPlayerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NextPlayer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 playerIndex = 1;</code>
     */
    int getPlayerIndex();
  }
  /**
   * Protobuf type {@code NextPlayer}
   */
  public  static final class NextPlayer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NextPlayer)
      NextPlayerOrBuilder {
    // Use NextPlayer.newBuilder() to construct.
    private NextPlayer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NextPlayer() {
      playerIndex_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private NextPlayer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              playerIndex_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kstn.game.logic.playing_event.player.PlayerMessage.internal_static_NextPlayer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kstn.game.logic.playing_event.player.PlayerMessage.internal_static_NextPlayer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer.class, kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer.Builder.class);
    }

    public static final int PLAYERINDEX_FIELD_NUMBER = 1;
    private int playerIndex_;
    /**
     * <code>int32 playerIndex = 1;</code>
     */
    public int getPlayerIndex() {
      return playerIndex_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (playerIndex_ != 0) {
        output.writeInt32(1, playerIndex_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (playerIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, playerIndex_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer)) {
        return super.equals(obj);
      }
      kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer other = (kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer) obj;

      boolean result = true;
      result = result && (getPlayerIndex()
          == other.getPlayerIndex());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLAYERINDEX_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerIndex();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NextPlayer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NextPlayer)
        kstn.game.logic.playing_event.player.PlayerMessage.NextPlayerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kstn.game.logic.playing_event.player.PlayerMessage.internal_static_NextPlayer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kstn.game.logic.playing_event.player.PlayerMessage.internal_static_NextPlayer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer.class, kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer.Builder.class);
      }

      // Construct using kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        playerIndex_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kstn.game.logic.playing_event.player.PlayerMessage.internal_static_NextPlayer_descriptor;
      }

      public kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer getDefaultInstanceForType() {
        return kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer.getDefaultInstance();
      }

      public kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer build() {
        kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer buildPartial() {
        kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer result = new kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer(this);
        result.playerIndex_ = playerIndex_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer) {
          return mergeFrom((kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer other) {
        if (other == kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer.getDefaultInstance()) return this;
        if (other.getPlayerIndex() != 0) {
          setPlayerIndex(other.getPlayerIndex());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int playerIndex_ ;
      /**
       * <code>int32 playerIndex = 1;</code>
       */
      public int getPlayerIndex() {
        return playerIndex_;
      }
      /**
       * <code>int32 playerIndex = 1;</code>
       */
      public Builder setPlayerIndex(int value) {
        
        playerIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 playerIndex = 1;</code>
       */
      public Builder clearPlayerIndex() {
        
        playerIndex_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:NextPlayer)
    }

    // @@protoc_insertion_point(class_scope:NextPlayer)
    private static final kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer();
    }

    public static kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NextPlayer>
        PARSER = new com.google.protobuf.AbstractParser<NextPlayer>() {
      public NextPlayer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NextPlayer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NextPlayer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NextPlayer> getParserForType() {
      return PARSER;
    }

    public kstn.game.logic.playing_event.player.PlayerMessage.NextPlayer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlayerActivateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerActivate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 playerIndex = 1;</code>
     */
    int getPlayerIndex();
  }
  /**
   * Protobuf type {@code PlayerActivate}
   */
  public  static final class PlayerActivate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PlayerActivate)
      PlayerActivateOrBuilder {
    // Use PlayerActivate.newBuilder() to construct.
    private PlayerActivate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerActivate() {
      playerIndex_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PlayerActivate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              playerIndex_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kstn.game.logic.playing_event.player.PlayerMessage.internal_static_PlayerActivate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kstn.game.logic.playing_event.player.PlayerMessage.internal_static_PlayerActivate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate.class, kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate.Builder.class);
    }

    public static final int PLAYERINDEX_FIELD_NUMBER = 1;
    private int playerIndex_;
    /**
     * <code>int32 playerIndex = 1;</code>
     */
    public int getPlayerIndex() {
      return playerIndex_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (playerIndex_ != 0) {
        output.writeInt32(1, playerIndex_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (playerIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, playerIndex_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate)) {
        return super.equals(obj);
      }
      kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate other = (kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate) obj;

      boolean result = true;
      result = result && (getPlayerIndex()
          == other.getPlayerIndex());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLAYERINDEX_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerIndex();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerActivate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerActivate)
        kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kstn.game.logic.playing_event.player.PlayerMessage.internal_static_PlayerActivate_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kstn.game.logic.playing_event.player.PlayerMessage.internal_static_PlayerActivate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate.class, kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate.Builder.class);
      }

      // Construct using kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        playerIndex_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kstn.game.logic.playing_event.player.PlayerMessage.internal_static_PlayerActivate_descriptor;
      }

      public kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate getDefaultInstanceForType() {
        return kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate.getDefaultInstance();
      }

      public kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate build() {
        kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate buildPartial() {
        kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate result = new kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate(this);
        result.playerIndex_ = playerIndex_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate) {
          return mergeFrom((kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate other) {
        if (other == kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate.getDefaultInstance()) return this;
        if (other.getPlayerIndex() != 0) {
          setPlayerIndex(other.getPlayerIndex());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int playerIndex_ ;
      /**
       * <code>int32 playerIndex = 1;</code>
       */
      public int getPlayerIndex() {
        return playerIndex_;
      }
      /**
       * <code>int32 playerIndex = 1;</code>
       */
      public Builder setPlayerIndex(int value) {
        
        playerIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 playerIndex = 1;</code>
       */
      public Builder clearPlayerIndex() {
        
        playerIndex_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PlayerActivate)
    }

    // @@protoc_insertion_point(class_scope:PlayerActivate)
    private static final kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate();
    }

    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerActivate>
        PARSER = new com.google.protobuf.AbstractParser<PlayerActivate>() {
      public PlayerActivate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PlayerActivate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerActivate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerActivate> getParserForType() {
      return PARSER;
    }

    public kstn.game.logic.playing_event.player.PlayerMessage.PlayerActivate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlayerDeactivateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerDeactivate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 playerIndex = 1;</code>
     */
    int getPlayerIndex();
  }
  /**
   * Protobuf type {@code PlayerDeactivate}
   */
  public  static final class PlayerDeactivate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PlayerDeactivate)
      PlayerDeactivateOrBuilder {
    // Use PlayerDeactivate.newBuilder() to construct.
    private PlayerDeactivate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerDeactivate() {
      playerIndex_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PlayerDeactivate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              playerIndex_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kstn.game.logic.playing_event.player.PlayerMessage.internal_static_PlayerDeactivate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kstn.game.logic.playing_event.player.PlayerMessage.internal_static_PlayerDeactivate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate.class, kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate.Builder.class);
    }

    public static final int PLAYERINDEX_FIELD_NUMBER = 1;
    private int playerIndex_;
    /**
     * <code>int32 playerIndex = 1;</code>
     */
    public int getPlayerIndex() {
      return playerIndex_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (playerIndex_ != 0) {
        output.writeInt32(1, playerIndex_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (playerIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, playerIndex_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate)) {
        return super.equals(obj);
      }
      kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate other = (kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate) obj;

      boolean result = true;
      result = result && (getPlayerIndex()
          == other.getPlayerIndex());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLAYERINDEX_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerIndex();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerDeactivate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerDeactivate)
        kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kstn.game.logic.playing_event.player.PlayerMessage.internal_static_PlayerDeactivate_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kstn.game.logic.playing_event.player.PlayerMessage.internal_static_PlayerDeactivate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate.class, kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate.Builder.class);
      }

      // Construct using kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        playerIndex_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kstn.game.logic.playing_event.player.PlayerMessage.internal_static_PlayerDeactivate_descriptor;
      }

      public kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate getDefaultInstanceForType() {
        return kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate.getDefaultInstance();
      }

      public kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate build() {
        kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate buildPartial() {
        kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate result = new kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate(this);
        result.playerIndex_ = playerIndex_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate) {
          return mergeFrom((kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate other) {
        if (other == kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate.getDefaultInstance()) return this;
        if (other.getPlayerIndex() != 0) {
          setPlayerIndex(other.getPlayerIndex());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int playerIndex_ ;
      /**
       * <code>int32 playerIndex = 1;</code>
       */
      public int getPlayerIndex() {
        return playerIndex_;
      }
      /**
       * <code>int32 playerIndex = 1;</code>
       */
      public Builder setPlayerIndex(int value) {
        
        playerIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 playerIndex = 1;</code>
       */
      public Builder clearPlayerIndex() {
        
        playerIndex_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PlayerDeactivate)
    }

    // @@protoc_insertion_point(class_scope:PlayerDeactivate)
    private static final kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate();
    }

    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerDeactivate>
        PARSER = new com.google.protobuf.AbstractParser<PlayerDeactivate>() {
      public PlayerDeactivate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PlayerDeactivate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerDeactivate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerDeactivate> getParserForType() {
      return PARSER;
    }

    public kstn.game.logic.playing_event.player.PlayerMessage.PlayerDeactivate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlayerReadyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerReady)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 ipAddress = 1;</code>
     */
    int getIpAddress();
  }
  /**
   * Protobuf type {@code PlayerReady}
   */
  public  static final class PlayerReady extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PlayerReady)
      PlayerReadyOrBuilder {
    // Use PlayerReady.newBuilder() to construct.
    private PlayerReady(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerReady() {
      ipAddress_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PlayerReady(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              ipAddress_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kstn.game.logic.playing_event.player.PlayerMessage.internal_static_PlayerReady_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kstn.game.logic.playing_event.player.PlayerMessage.internal_static_PlayerReady_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady.class, kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady.Builder.class);
    }

    public static final int IPADDRESS_FIELD_NUMBER = 1;
    private int ipAddress_;
    /**
     * <code>int32 ipAddress = 1;</code>
     */
    public int getIpAddress() {
      return ipAddress_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ipAddress_ != 0) {
        output.writeInt32(1, ipAddress_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ipAddress_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ipAddress_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady)) {
        return super.equals(obj);
      }
      kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady other = (kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady) obj;

      boolean result = true;
      result = result && (getIpAddress()
          == other.getIpAddress());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IPADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getIpAddress();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerReady}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerReady)
        kstn.game.logic.playing_event.player.PlayerMessage.PlayerReadyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kstn.game.logic.playing_event.player.PlayerMessage.internal_static_PlayerReady_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kstn.game.logic.playing_event.player.PlayerMessage.internal_static_PlayerReady_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady.class, kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady.Builder.class);
      }

      // Construct using kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        ipAddress_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kstn.game.logic.playing_event.player.PlayerMessage.internal_static_PlayerReady_descriptor;
      }

      public kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady getDefaultInstanceForType() {
        return kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady.getDefaultInstance();
      }

      public kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady build() {
        kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady buildPartial() {
        kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady result = new kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady(this);
        result.ipAddress_ = ipAddress_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady) {
          return mergeFrom((kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady other) {
        if (other == kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady.getDefaultInstance()) return this;
        if (other.getIpAddress() != 0) {
          setIpAddress(other.getIpAddress());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int ipAddress_ ;
      /**
       * <code>int32 ipAddress = 1;</code>
       */
      public int getIpAddress() {
        return ipAddress_;
      }
      /**
       * <code>int32 ipAddress = 1;</code>
       */
      public Builder setIpAddress(int value) {
        
        ipAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ipAddress = 1;</code>
       */
      public Builder clearIpAddress() {
        
        ipAddress_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PlayerReady)
    }

    // @@protoc_insertion_point(class_scope:PlayerReady)
    private static final kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady();
    }

    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerReady>
        PARSER = new com.google.protobuf.AbstractParser<PlayerReady>() {
      public PlayerReady parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PlayerReady(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerReady> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerReady> getParserForType() {
      return PARSER;
    }

    public kstn.game.logic.playing_event.player.PlayerMessage.PlayerReady getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlayerSetScoreOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerSetScore)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 score = 1;</code>
     */
    int getScore();
  }
  /**
   * Protobuf type {@code PlayerSetScore}
   */
  public  static final class PlayerSetScore extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PlayerSetScore)
      PlayerSetScoreOrBuilder {
    // Use PlayerSetScore.newBuilder() to construct.
    private PlayerSetScore(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerSetScore() {
      score_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PlayerSetScore(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              score_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kstn.game.logic.playing_event.player.PlayerMessage.internal_static_PlayerSetScore_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kstn.game.logic.playing_event.player.PlayerMessage.internal_static_PlayerSetScore_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore.class, kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore.Builder.class);
    }

    public static final int SCORE_FIELD_NUMBER = 1;
    private int score_;
    /**
     * <code>int32 score = 1;</code>
     */
    public int getScore() {
      return score_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (score_ != 0) {
        output.writeInt32(1, score_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (score_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, score_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore)) {
        return super.equals(obj);
      }
      kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore other = (kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore) obj;

      boolean result = true;
      result = result && (getScore()
          == other.getScore());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SCORE_FIELD_NUMBER;
      hash = (53 * hash) + getScore();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerSetScore}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerSetScore)
        kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScoreOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kstn.game.logic.playing_event.player.PlayerMessage.internal_static_PlayerSetScore_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kstn.game.logic.playing_event.player.PlayerMessage.internal_static_PlayerSetScore_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore.class, kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore.Builder.class);
      }

      // Construct using kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        score_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kstn.game.logic.playing_event.player.PlayerMessage.internal_static_PlayerSetScore_descriptor;
      }

      public kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore getDefaultInstanceForType() {
        return kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore.getDefaultInstance();
      }

      public kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore build() {
        kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore buildPartial() {
        kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore result = new kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore(this);
        result.score_ = score_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore) {
          return mergeFrom((kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore other) {
        if (other == kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore.getDefaultInstance()) return this;
        if (other.getScore() != 0) {
          setScore(other.getScore());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int score_ ;
      /**
       * <code>int32 score = 1;</code>
       */
      public int getScore() {
        return score_;
      }
      /**
       * <code>int32 score = 1;</code>
       */
      public Builder setScore(int value) {
        
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 score = 1;</code>
       */
      public Builder clearScore() {
        
        score_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PlayerSetScore)
    }

    // @@protoc_insertion_point(class_scope:PlayerSetScore)
    private static final kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore();
    }

    public static kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerSetScore>
        PARSER = new com.google.protobuf.AbstractParser<PlayerSetScore>() {
      public PlayerSetScore parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PlayerSetScore(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerSetScore> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerSetScore> getParserForType() {
      return PARSER;
    }

    public kstn.game.logic.playing_event.player.PlayerMessage.PlayerSetScore getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NextPlayer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NextPlayer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerActivate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlayerActivate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerDeactivate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlayerDeactivate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerReady_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlayerReady_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerSetScore_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlayerSetScore_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9kstn/game/logic/playing_event/player/p" +
      "layer_message.proto\"!\n\nNextPlayer\022\023\n\013pla" +
      "yerIndex\030\001 \001(\005\"%\n\016PlayerActivate\022\023\n\013play" +
      "erIndex\030\001 \001(\005\"\'\n\020PlayerDeactivate\022\023\n\013pla" +
      "yerIndex\030\001 \001(\005\" \n\013PlayerReady\022\021\n\tipAddre" +
      "ss\030\001 \001(\005\"\037\n\016PlayerSetScore\022\r\n\005score\030\001 \001(" +
      "\005B&\n$kstn.game.logic.playing_event.playe" +
      "rb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_NextPlayer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NextPlayer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NextPlayer_descriptor,
        new java.lang.String[] { "PlayerIndex", });
    internal_static_PlayerActivate_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PlayerActivate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlayerActivate_descriptor,
        new java.lang.String[] { "PlayerIndex", });
    internal_static_PlayerDeactivate_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PlayerDeactivate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlayerDeactivate_descriptor,
        new java.lang.String[] { "PlayerIndex", });
    internal_static_PlayerReady_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PlayerReady_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlayerReady_descriptor,
        new java.lang.String[] { "IpAddress", });
    internal_static_PlayerSetScore_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_PlayerSetScore_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlayerSetScore_descriptor,
        new java.lang.String[] { "Score", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
