// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kstn/game/logic/playing_event/room/room_message.proto

package kstn.game.logic.playing_event.room;

public final class RoomMessage {
  private RoomMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SawCreatedRoomOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SawCreatedRoom)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 ipAddress = 1;</code>
     */
    int getIpAddress();

    /**
     * <code>string roomName = 2;</code>
     */
    java.lang.String getRoomName();
    /**
     * <code>string roomName = 2;</code>
     */
    com.google.protobuf.ByteString
        getRoomNameBytes();

    /**
     * <code>int32 playerCount = 3;</code>
     */
    int getPlayerCount();
  }
  /**
   * Protobuf type {@code SawCreatedRoom}
   */
  public  static final class SawCreatedRoom extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SawCreatedRoom)
      SawCreatedRoomOrBuilder {
    // Use SawCreatedRoom.newBuilder() to construct.
    private SawCreatedRoom(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SawCreatedRoom() {
      ipAddress_ = 0;
      roomName_ = "";
      playerCount_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SawCreatedRoom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              ipAddress_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              roomName_ = s;
              break;
            }
            case 24: {

              playerCount_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kstn.game.logic.playing_event.room.RoomMessage.internal_static_SawCreatedRoom_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kstn.game.logic.playing_event.room.RoomMessage.internal_static_SawCreatedRoom_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom.class, kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom.Builder.class);
    }

    public static final int IPADDRESS_FIELD_NUMBER = 1;
    private int ipAddress_;
    /**
     * <code>int32 ipAddress = 1;</code>
     */
    public int getIpAddress() {
      return ipAddress_;
    }

    public static final int ROOMNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object roomName_;
    /**
     * <code>string roomName = 2;</code>
     */
    public java.lang.String getRoomName() {
      java.lang.Object ref = roomName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomName_ = s;
        return s;
      }
    }
    /**
     * <code>string roomName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRoomNameBytes() {
      java.lang.Object ref = roomName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAYERCOUNT_FIELD_NUMBER = 3;
    private int playerCount_;
    /**
     * <code>int32 playerCount = 3;</code>
     */
    public int getPlayerCount() {
      return playerCount_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ipAddress_ != 0) {
        output.writeInt32(1, ipAddress_);
      }
      if (!getRoomNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, roomName_);
      }
      if (playerCount_ != 0) {
        output.writeInt32(3, playerCount_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ipAddress_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ipAddress_);
      }
      if (!getRoomNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, roomName_);
      }
      if (playerCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, playerCount_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom)) {
        return super.equals(obj);
      }
      kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom other = (kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom) obj;

      boolean result = true;
      result = result && (getIpAddress()
          == other.getIpAddress());
      result = result && getRoomName()
          .equals(other.getRoomName());
      result = result && (getPlayerCount()
          == other.getPlayerCount());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IPADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getIpAddress();
      hash = (37 * hash) + ROOMNAME_FIELD_NUMBER;
      hash = (53 * hash) + getRoomName().hashCode();
      hash = (37 * hash) + PLAYERCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerCount();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SawCreatedRoom}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SawCreatedRoom)
        kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoomOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kstn.game.logic.playing_event.room.RoomMessage.internal_static_SawCreatedRoom_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kstn.game.logic.playing_event.room.RoomMessage.internal_static_SawCreatedRoom_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom.class, kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom.Builder.class);
      }

      // Construct using kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        ipAddress_ = 0;

        roomName_ = "";

        playerCount_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kstn.game.logic.playing_event.room.RoomMessage.internal_static_SawCreatedRoom_descriptor;
      }

      public kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom getDefaultInstanceForType() {
        return kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom.getDefaultInstance();
      }

      public kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom build() {
        kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom buildPartial() {
        kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom result = new kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom(this);
        result.ipAddress_ = ipAddress_;
        result.roomName_ = roomName_;
        result.playerCount_ = playerCount_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom) {
          return mergeFrom((kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom other) {
        if (other == kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom.getDefaultInstance()) return this;
        if (other.getIpAddress() != 0) {
          setIpAddress(other.getIpAddress());
        }
        if (!other.getRoomName().isEmpty()) {
          roomName_ = other.roomName_;
          onChanged();
        }
        if (other.getPlayerCount() != 0) {
          setPlayerCount(other.getPlayerCount());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int ipAddress_ ;
      /**
       * <code>int32 ipAddress = 1;</code>
       */
      public int getIpAddress() {
        return ipAddress_;
      }
      /**
       * <code>int32 ipAddress = 1;</code>
       */
      public Builder setIpAddress(int value) {
        
        ipAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ipAddress = 1;</code>
       */
      public Builder clearIpAddress() {
        
        ipAddress_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object roomName_ = "";
      /**
       * <code>string roomName = 2;</code>
       */
      public java.lang.String getRoomName() {
        java.lang.Object ref = roomName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          roomName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string roomName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRoomNameBytes() {
        java.lang.Object ref = roomName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          roomName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string roomName = 2;</code>
       */
      public Builder setRoomName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        roomName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string roomName = 2;</code>
       */
      public Builder clearRoomName() {
        
        roomName_ = getDefaultInstance().getRoomName();
        onChanged();
        return this;
      }
      /**
       * <code>string roomName = 2;</code>
       */
      public Builder setRoomNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        roomName_ = value;
        onChanged();
        return this;
      }

      private int playerCount_ ;
      /**
       * <code>int32 playerCount = 3;</code>
       */
      public int getPlayerCount() {
        return playerCount_;
      }
      /**
       * <code>int32 playerCount = 3;</code>
       */
      public Builder setPlayerCount(int value) {
        
        playerCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 playerCount = 3;</code>
       */
      public Builder clearPlayerCount() {
        
        playerCount_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:SawCreatedRoom)
    }

    // @@protoc_insertion_point(class_scope:SawCreatedRoom)
    private static final kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom();
    }

    public static kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SawCreatedRoom>
        PARSER = new com.google.protobuf.AbstractParser<SawCreatedRoom>() {
      public SawCreatedRoom parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SawCreatedRoom(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SawCreatedRoom> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SawCreatedRoom> getParserForType() {
      return PARSER;
    }

    public kstn.game.logic.playing_event.room.RoomMessage.SawCreatedRoom getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SawCreatedRoom_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SawCreatedRoom_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5kstn/game/logic/playing_event/room/roo" +
      "m_message.proto\"J\n\016SawCreatedRoom\022\021\n\tipA" +
      "ddress\030\001 \001(\005\022\020\n\010roomName\030\002 \001(\t\022\023\n\013player" +
      "Count\030\003 \001(\005B$\n\"kstn.game.logic.playing_e" +
      "vent.roomb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SawCreatedRoom_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SawCreatedRoom_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SawCreatedRoom_descriptor,
        new java.lang.String[] { "IpAddress", "RoomName", "PlayerCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
